version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: harness-admin-postgres
    environment:
      POSTGRES_DB: harness_admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "33204:5432"
    volumes:
      - harness-admin-postgres:/var/lib/postgresql/data

volumes:
  harness-admin-postgres:
