services:
  harness-portal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "33210:80"
      - "33211:443"
    volumes:
      - ./certs:/etc/nginx/certs
    restart: unless-stopped
